[build]
  base = "/"
  command = "gunicorn app:app"
  publish = "static"

[functions]
  [functions.api]
    path = "app.py"
    handler = "app.app"
    environment = { FLASK_APP = "app.py", FLASK_ENV = "production", FLASK_RUN_HOST = "0.0.0.0" }

[context.production.environment]
FLASK_APP = "app.py"
FLASK_ENV = "production"
FLASK_RUN_HOST = "0.0.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.text-summarizer.rinka.windsurf.build/:splat"
  status = 200
  force = true
